CVC4 / Yices2 as part of CI
ehildenb/maude pull request #25
Opened 2018-09-24 01:52 UTC by nishantjr

2018-09-24 01:56 UTC, nishantjr commented
Note that buildbot needs to use `./build test-all` for this to run `smtTest`

2018-09-24 03:08 UTC, ehildenb requested changes
Looks good, minor changes.

I would also like a `./build test-smt` option which ran just the SMT tests. `./build test-all` can call that function directly.

2018-09-24 03:08 UTC, ehildenb commented on build
> +    test-all)       build_test_all "$@" ;;
Please line up the `$@` and make sure that all options here are documented below.

2018-09-25 14:49 UTC, ehildenb approved these changes

2018-09-25 14:50 UTC, ehildenb commented
@nishantjr I've updaded Buildbot to include a step for running the SMT tests as well.

I prefer to keep it separated out into build steps so it's easier to see which step Buildbot fails on.

2018-09-25 16:59 UTC, ehildenb commented
A small formatting error caused a weird bug in `./configure`, but it should be fixed now. Fingers crossed!

2018-09-27 19:47 UTC, merged